MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../models/FCOS_R_50_FPN_1x.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TRAIN: ("coco_2017_train", )
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
ROI_HEADS:
  USE_FPN: True
ROI_BOX_HEAD:
  POOLER_RESOLUTION: 7
  POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
  POOLER_SAMPLING_RATIO: 2
  FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
  PREDICTOR: "FPNPredictor"
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "constant"
OUTPUT_DIR: "../checkpoints"